name: 'GCP Terraform'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      auto_approve:
        description: 'Should we auto-approve apply?'
        required: true
        default: 'false'

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform-gcp:
    name: 'Terraform-GCP'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate Google Cloud using Workload Identity Federation
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v2 
      with:
        workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL }}

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{secrets.TF_API_TOKEN }}

    # # Terraform Format (checks for code formatting)
    # - name: Terraform Fmt
    #   run: terraform fmt -check -diff

    # Terraform Init (initializes the working directory)
    - name: Terraform Init
      run: terraform init 

    # Terraform Validate (validates the configuration files)
    - name: Terraform Validate
      run: terraform validate

    # Terraform Plan (creates an execution plan)
    - name: Terraform Plan
      run: terraform plan -input=false

    # Manual Approval Step (Mimic Approval via 'auto_approve' parameter)
    - name: Terraform Apply Now
      run: terraform apply --auto-approve -input=false

    - name: Wait for 30 seconds before destroy
      run: |
        echo "Sleeping now for 30 seconds before destroy..."
        sleep 30
 
    # Terraform Destroy (destroys the resources after 10 minutes)
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false