name: 'GCP Terraform'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate Google Cloud using Workload Identity Federation
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v2 
      with:
        workload_identity_provider: 'projects/330224828591/locations/global/workloadIdentityPools/terrafom-github/providers/github'
        service_account: 'terraform-sa@fifth-catcher-418014.iam.gserviceaccount.com'

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Terraform Format (checks for code formatting)
    - name: Terraform Fmt
      run: terraform fmt -check -diff


    # Terraform Init (initializes the working directory)
    - name: Terraform Init
      run: terraform init 
    # Terraform Validate (validates the configuration files)
    - name: Terraform Validate
      run: terraform validate


    # Terraform Plan (creates an execution plan)
    - name: Terraform Plan
      run: terraform plan -input=false

    # Terraform Apply (applies the plan)
    - name: Terraform Apply
      run: terraform apply -input=true

    # Wait for 10 minutes before running destroy
    - name: Wait for 30 seconds
      run: sleep 30  # 600 seconds = 10 minutes

    # Terraform Destroy (destroys the resources after 10 minutes)
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
